// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: paymentpb.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrderItemByUserAndProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ProductID     string                 `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderItemByUserAndProductIDRequest) Reset() {
	*x = GetOrderItemByUserAndProductIDRequest{}
	mi := &file_paymentpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderItemByUserAndProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderItemByUserAndProductIDRequest) ProtoMessage() {}

func (x *GetOrderItemByUserAndProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderItemByUserAndProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderItemByUserAndProductIDRequest) Descriptor() ([]byte, []int) {
	return file_paymentpb_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderItemByUserAndProductIDRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetOrderItemByUserAndProductIDRequest) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type GetOrderItemByUserAndProductIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderID       string                 `protobuf:"bytes,2,opt,name=orderID,proto3" json:"orderID,omitempty"`
	ProductID     string                 `protobuf:"bytes,3,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,6,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderItemByUserAndProductIDResponse) Reset() {
	*x = GetOrderItemByUserAndProductIDResponse{}
	mi := &file_paymentpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderItemByUserAndProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderItemByUserAndProductIDResponse) ProtoMessage() {}

func (x *GetOrderItemByUserAndProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderItemByUserAndProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderItemByUserAndProductIDResponse) Descriptor() ([]byte, []int) {
	return file_paymentpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderItemByUserAndProductIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderItemByUserAndProductIDResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *GetOrderItemByUserAndProductIDResponse) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *GetOrderItemByUserAndProductIDResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetOrderItemByUserAndProductIDResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetOrderItemByUserAndProductIDResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetOrderItemByUserAndProductIDResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderItemByUserAndProductIDResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetOrderItemByUserAndProductIDResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_paymentpb_proto protoreflect.FileDescriptor

const file_paymentpb_proto_rawDesc = "" +
	"\n" +
	"\x0fpaymentpb.proto\x12\tpaymentpb\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"%GetOrderItemByUserAndProductIDRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1c\n" +
	"\tproductID\x18\x02 \x01(\tR\tproductID\"\xd0\x02\n" +
	"&GetOrderItemByUserAndProductIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aorderID\x18\x02 \x01(\tR\aorderID\x12\x1c\n" +
	"\tproductID\x18\x03 \x01(\tR\tproductID\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12 \n" +
	"\vtotalAmount\x18\x06 \x01(\x01R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x128\n" +
	"\tcreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\x98\x01\n" +
	"\x0ePaymentService\x12\x85\x01\n" +
	"\x1eGetOrderItemByUserAndProductID\x120.paymentpb.GetOrderItemByUserAndProductIDRequest\x1a1.paymentpb.GetOrderItemByUserAndProductIDResponseB;Z9github.com/amankhys/brocamp/ecom/pkg/pb/payment/paymentpbb\x06proto3"

var (
	file_paymentpb_proto_rawDescOnce sync.Once
	file_paymentpb_proto_rawDescData []byte
)

func file_paymentpb_proto_rawDescGZIP() []byte {
	file_paymentpb_proto_rawDescOnce.Do(func() {
		file_paymentpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentpb_proto_rawDesc), len(file_paymentpb_proto_rawDesc)))
	})
	return file_paymentpb_proto_rawDescData
}

var file_paymentpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paymentpb_proto_goTypes = []any{
	(*GetOrderItemByUserAndProductIDRequest)(nil),  // 0: paymentpb.GetOrderItemByUserAndProductIDRequest
	(*GetOrderItemByUserAndProductIDResponse)(nil), // 1: paymentpb.GetOrderItemByUserAndProductIDResponse
	(*timestamppb.Timestamp)(nil),                  // 2: google.protobuf.Timestamp
}
var file_paymentpb_proto_depIdxs = []int32{
	2, // 0: paymentpb.GetOrderItemByUserAndProductIDResponse.createdAt:type_name -> google.protobuf.Timestamp
	2, // 1: paymentpb.GetOrderItemByUserAndProductIDResponse.updatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: paymentpb.PaymentService.GetOrderItemByUserAndProductID:input_type -> paymentpb.GetOrderItemByUserAndProductIDRequest
	1, // 3: paymentpb.PaymentService.GetOrderItemByUserAndProductID:output_type -> paymentpb.GetOrderItemByUserAndProductIDResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_paymentpb_proto_init() }
func file_paymentpb_proto_init() {
	if File_paymentpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentpb_proto_rawDesc), len(file_paymentpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paymentpb_proto_goTypes,
		DependencyIndexes: file_paymentpb_proto_depIdxs,
		MessageInfos:      file_paymentpb_proto_msgTypes,
	}.Build()
	File_paymentpb_proto = out.File
	file_paymentpb_proto_goTypes = nil
	file_paymentpb_proto_depIdxs = nil
}
