// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCateogry = `-- name: AddCateogry :one
insert into categories
(name) values ($1)
returning id, name, is_deleted, created_at, updated_at
`

func (q *Queries) AddCateogry(ctx context.Context, name string) (Category, error) {
	row := q.queryRow(ctx, q.addCateogryStmt, addCateogry, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllCategoriesForProductByID = `-- name: DeleteAllCategoriesForProductByID :exec
delete from category_items
where product_id = $1
`

func (q *Queries) DeleteAllCategoriesForProductByID(ctx context.Context, productID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteAllCategoriesForProductByIDStmt, deleteAllCategoriesForProductByID, productID)
	return err
}

const deleteCategoryByName = `-- name: DeleteCategoryByName :one
update categories
set is_deleted = true, updated_at = current_timestamp
where name = $1
returning id, name, is_deleted, created_at, updated_at
`

func (q *Queries) DeleteCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.queryRow(ctx, q.deleteCategoryByNameStmt, deleteCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const editCategoryNameByName = `-- name: EditCategoryNameByName :one
update categories
set name = $1, updated_at = current_timestamp
where name = $2 and is_deleted = false
returning id, name, is_deleted, created_at, updated_at
`

type EditCategoryNameByNameParams struct {
	NewName string `json:"new_name"`
	Name    string `json:"name"`
}

func (q *Queries) EditCategoryNameByName(ctx context.Context, arg EditCategoryNameByNameParams) (Category, error) {
	row := q.queryRow(ctx, q.editCategoryNameByNameStmt, editCategoryNameByName, arg.NewName, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCategories = `-- name: GetAllCategories :many
select id, name, is_deleted, created_at, updated_at from categories
where is_deleted = false
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.query(ctx, q.getAllCategoriesStmt, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategoriesForAdmin = `-- name: GetAllCategoriesForAdmin :many
select id, name, is_deleted, created_at, updated_at from categories
`

func (q *Queries) GetAllCategoriesForAdmin(ctx context.Context) ([]Category, error) {
	rows, err := q.query(ctx, q.getAllCategoriesForAdminStmt, getAllCategoriesForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
select id, name, is_deleted, created_at, updated_at from categories
where id = $1 and is_deleted = false
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.queryRow(ctx, q.getCategoryByIDStmt, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
select id, name, is_deleted, created_at, updated_at from categories
where name = $1 and is_deleted = false
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.queryRow(ctx, q.getCategoryByNameStmt, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryNamesOfProductByID = `-- name: GetCategoryNamesOfProductByID :many
select c.name from category_items ci
inner join categories c
on ci.category_id = c.id
where ci.product_id = $1 and c.is_deleted = false
`

func (q *Queries) GetCategoryNamesOfProductByID(ctx context.Context, productID uuid.UUID) ([]string, error) {
	rows, err := q.query(ctx, q.getCategoryNamesOfProductByIDStmt, getCategoryNamesOfProductByID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsByCategoryName = `-- name: GetProductsByCategoryName :many
select p.id, p.name, p.description, p.price, p.stock, p.seller_id, p.created_at, p.updated_at from category_items ci
inner join products p
on ci.product_id = p.id
inner join categories c
on ci.category_id = c.id
where c.name = $1 and c.is_deleted = false and p.is_deleted = false
`

type GetProductsByCategoryNameRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       float64   `json:"price"`
	Stock       int32     `json:"stock"`
	SellerID    uuid.UUID `json:"seller_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetProductsByCategoryName(ctx context.Context, name string) ([]GetProductsByCategoryNameRow, error) {
	rows, err := q.query(ctx, q.getProductsByCategoryNameStmt, getProductsByCategoryName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsByCategoryNameRow{}
	for rows.Next() {
		var i GetProductsByCategoryNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.SellerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
