// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCateogryStmt, err = db.PrepareContext(ctx, addCateogry); err != nil {
		return nil, fmt.Errorf("error preparing query AddCateogry: %w", err)
	}
	if q.addProductStmt, err = db.PrepareContext(ctx, addProduct); err != nil {
		return nil, fmt.Errorf("error preparing query AddProduct: %w", err)
	}
	if q.addProductReviewWithCommmentStmt, err = db.PrepareContext(ctx, addProductReviewWithCommment); err != nil {
		return nil, fmt.Errorf("error preparing query AddProductReviewWithCommment: %w", err)
	}
	if q.addProductReviewWithoutCommentStmt, err = db.PrepareContext(ctx, addProductReviewWithoutComment); err != nil {
		return nil, fmt.Errorf("error preparing query AddProductReviewWithoutComment: %w", err)
	}
	if q.addProductToCategoryByCategoryNameStmt, err = db.PrepareContext(ctx, addProductToCategoryByCategoryName); err != nil {
		return nil, fmt.Errorf("error preparing query AddProductToCategoryByCategoryName: %w", err)
	}
	if q.addProductToCategoryByIDStmt, err = db.PrepareContext(ctx, addProductToCategoryByID); err != nil {
		return nil, fmt.Errorf("error preparing query AddProductToCategoryByID: %w", err)
	}
	if q.addWishListItemStmt, err = db.PrepareContext(ctx, addWishListItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddWishListItem: %w", err)
	}
	if q.decProductStockByIDStmt, err = db.PrepareContext(ctx, decProductStockByID); err != nil {
		return nil, fmt.Errorf("error preparing query DecProductStockByID: %w", err)
	}
	if q.deleteAllCategoriesForProductByIDStmt, err = db.PrepareContext(ctx, deleteAllCategoriesForProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllCategoriesForProductByID: %w", err)
	}
	if q.deleteAllWishListItemsByUserIDStmt, err = db.PrepareContext(ctx, deleteAllWishListItemsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllWishListItemsByUserID: %w", err)
	}
	if q.deleteCategoryByNameStmt, err = db.PrepareContext(ctx, deleteCategoryByName); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCategoryByName: %w", err)
	}
	if q.deleteProductByIDStmt, err = db.PrepareContext(ctx, deleteProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductByID: %w", err)
	}
	if q.deleteProductsBySellerIDStmt, err = db.PrepareContext(ctx, deleteProductsBySellerID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductsBySellerID: %w", err)
	}
	if q.deleteWishListItemByUserAndProductIDStmt, err = db.PrepareContext(ctx, deleteWishListItemByUserAndProductID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteWishListItemByUserAndProductID: %w", err)
	}
	if q.editCategoryNameByNameStmt, err = db.PrepareContext(ctx, editCategoryNameByName); err != nil {
		return nil, fmt.Errorf("error preparing query EditCategoryNameByName: %w", err)
	}
	if q.editProductByIDStmt, err = db.PrepareContext(ctx, editProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditProductByID: %w", err)
	}
	if q.getAllCategoriesStmt, err = db.PrepareContext(ctx, getAllCategories); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllCategories: %w", err)
	}
	if q.getAllCategoriesForAdminStmt, err = db.PrepareContext(ctx, getAllCategoriesForAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllCategoriesForAdmin: %w", err)
	}
	if q.getAllProductsStmt, err = db.PrepareContext(ctx, getAllProducts); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllProducts: %w", err)
	}
	if q.getAllProductsForAdminStmt, err = db.PrepareContext(ctx, getAllProductsForAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllProductsForAdmin: %w", err)
	}
	if q.getAllWishListItemsByUserIDStmt, err = db.PrepareContext(ctx, getAllWishListItemsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllWishListItemsByUserID: %w", err)
	}
	if q.getAllWishListItemsWithProductNameByUserIDStmt, err = db.PrepareContext(ctx, getAllWishListItemsWithProductNameByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllWishListItemsWithProductNameByUserID: %w", err)
	}
	if q.getCategoryByIDStmt, err = db.PrepareContext(ctx, getCategoryByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryByID: %w", err)
	}
	if q.getCategoryByNameStmt, err = db.PrepareContext(ctx, getCategoryByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryByName: %w", err)
	}
	if q.getCategoryNamesOfProductByIDStmt, err = db.PrepareContext(ctx, getCategoryNamesOfProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryNamesOfProductByID: %w", err)
	}
	if q.getProductAndCategoryNameByIDStmt, err = db.PrepareContext(ctx, getProductAndCategoryNameByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductAndCategoryNameByID: %w", err)
	}
	if q.getProductAverageRatingAndTotalRatingStmt, err = db.PrepareContext(ctx, getProductAverageRatingAndTotalRating); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductAverageRatingAndTotalRating: %w", err)
	}
	if q.getProductByIDStmt, err = db.PrepareContext(ctx, getProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductByID: %w", err)
	}
	if q.getProductReviewsStmt, err = db.PrepareContext(ctx, getProductReviews); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductReviews: %w", err)
	}
	if q.getProductsByCategoryNameStmt, err = db.PrepareContext(ctx, getProductsByCategoryName); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductsByCategoryName: %w", err)
	}
	if q.getProductsBySellerIDStmt, err = db.PrepareContext(ctx, getProductsBySellerID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductsBySellerID: %w", err)
	}
	if q.getReviewByUserAndProductIDStmt, err = db.PrepareContext(ctx, getReviewByUserAndProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReviewByUserAndProductID: %w", err)
	}
	if q.getWishListItemByUserAndProductIDStmt, err = db.PrepareContext(ctx, getWishListItemByUserAndProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetWishListItemByUserAndProductID: %w", err)
	}
	if q.incProductStockByIDStmt, err = db.PrepareContext(ctx, incProductStockByID); err != nil {
		return nil, fmt.Errorf("error preparing query IncProductStockByID: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCateogryStmt != nil {
		if cerr := q.addCateogryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCateogryStmt: %w", cerr)
		}
	}
	if q.addProductStmt != nil {
		if cerr := q.addProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addProductStmt: %w", cerr)
		}
	}
	if q.addProductReviewWithCommmentStmt != nil {
		if cerr := q.addProductReviewWithCommmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addProductReviewWithCommmentStmt: %w", cerr)
		}
	}
	if q.addProductReviewWithoutCommentStmt != nil {
		if cerr := q.addProductReviewWithoutCommentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addProductReviewWithoutCommentStmt: %w", cerr)
		}
	}
	if q.addProductToCategoryByCategoryNameStmt != nil {
		if cerr := q.addProductToCategoryByCategoryNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addProductToCategoryByCategoryNameStmt: %w", cerr)
		}
	}
	if q.addProductToCategoryByIDStmt != nil {
		if cerr := q.addProductToCategoryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addProductToCategoryByIDStmt: %w", cerr)
		}
	}
	if q.addWishListItemStmt != nil {
		if cerr := q.addWishListItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addWishListItemStmt: %w", cerr)
		}
	}
	if q.decProductStockByIDStmt != nil {
		if cerr := q.decProductStockByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing decProductStockByIDStmt: %w", cerr)
		}
	}
	if q.deleteAllCategoriesForProductByIDStmt != nil {
		if cerr := q.deleteAllCategoriesForProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllCategoriesForProductByIDStmt: %w", cerr)
		}
	}
	if q.deleteAllWishListItemsByUserIDStmt != nil {
		if cerr := q.deleteAllWishListItemsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllWishListItemsByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteCategoryByNameStmt != nil {
		if cerr := q.deleteCategoryByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCategoryByNameStmt: %w", cerr)
		}
	}
	if q.deleteProductByIDStmt != nil {
		if cerr := q.deleteProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductByIDStmt: %w", cerr)
		}
	}
	if q.deleteProductsBySellerIDStmt != nil {
		if cerr := q.deleteProductsBySellerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductsBySellerIDStmt: %w", cerr)
		}
	}
	if q.deleteWishListItemByUserAndProductIDStmt != nil {
		if cerr := q.deleteWishListItemByUserAndProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteWishListItemByUserAndProductIDStmt: %w", cerr)
		}
	}
	if q.editCategoryNameByNameStmt != nil {
		if cerr := q.editCategoryNameByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editCategoryNameByNameStmt: %w", cerr)
		}
	}
	if q.editProductByIDStmt != nil {
		if cerr := q.editProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editProductByIDStmt: %w", cerr)
		}
	}
	if q.getAllCategoriesStmt != nil {
		if cerr := q.getAllCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllCategoriesStmt: %w", cerr)
		}
	}
	if q.getAllCategoriesForAdminStmt != nil {
		if cerr := q.getAllCategoriesForAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllCategoriesForAdminStmt: %w", cerr)
		}
	}
	if q.getAllProductsStmt != nil {
		if cerr := q.getAllProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllProductsStmt: %w", cerr)
		}
	}
	if q.getAllProductsForAdminStmt != nil {
		if cerr := q.getAllProductsForAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllProductsForAdminStmt: %w", cerr)
		}
	}
	if q.getAllWishListItemsByUserIDStmt != nil {
		if cerr := q.getAllWishListItemsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllWishListItemsByUserIDStmt: %w", cerr)
		}
	}
	if q.getAllWishListItemsWithProductNameByUserIDStmt != nil {
		if cerr := q.getAllWishListItemsWithProductNameByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllWishListItemsWithProductNameByUserIDStmt: %w", cerr)
		}
	}
	if q.getCategoryByIDStmt != nil {
		if cerr := q.getCategoryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryByIDStmt: %w", cerr)
		}
	}
	if q.getCategoryByNameStmt != nil {
		if cerr := q.getCategoryByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryByNameStmt: %w", cerr)
		}
	}
	if q.getCategoryNamesOfProductByIDStmt != nil {
		if cerr := q.getCategoryNamesOfProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryNamesOfProductByIDStmt: %w", cerr)
		}
	}
	if q.getProductAndCategoryNameByIDStmt != nil {
		if cerr := q.getProductAndCategoryNameByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductAndCategoryNameByIDStmt: %w", cerr)
		}
	}
	if q.getProductAverageRatingAndTotalRatingStmt != nil {
		if cerr := q.getProductAverageRatingAndTotalRatingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductAverageRatingAndTotalRatingStmt: %w", cerr)
		}
	}
	if q.getProductByIDStmt != nil {
		if cerr := q.getProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductByIDStmt: %w", cerr)
		}
	}
	if q.getProductReviewsStmt != nil {
		if cerr := q.getProductReviewsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductReviewsStmt: %w", cerr)
		}
	}
	if q.getProductsByCategoryNameStmt != nil {
		if cerr := q.getProductsByCategoryNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductsByCategoryNameStmt: %w", cerr)
		}
	}
	if q.getProductsBySellerIDStmt != nil {
		if cerr := q.getProductsBySellerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductsBySellerIDStmt: %w", cerr)
		}
	}
	if q.getReviewByUserAndProductIDStmt != nil {
		if cerr := q.getReviewByUserAndProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReviewByUserAndProductIDStmt: %w", cerr)
		}
	}
	if q.getWishListItemByUserAndProductIDStmt != nil {
		if cerr := q.getWishListItemByUserAndProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWishListItemByUserAndProductIDStmt: %w", cerr)
		}
	}
	if q.incProductStockByIDStmt != nil {
		if cerr := q.incProductStockByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incProductStockByIDStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                             DBTX
	tx                                             *sql.Tx
	addCateogryStmt                                *sql.Stmt
	addProductStmt                                 *sql.Stmt
	addProductReviewWithCommmentStmt               *sql.Stmt
	addProductReviewWithoutCommentStmt             *sql.Stmt
	addProductToCategoryByCategoryNameStmt         *sql.Stmt
	addProductToCategoryByIDStmt                   *sql.Stmt
	addWishListItemStmt                            *sql.Stmt
	decProductStockByIDStmt                        *sql.Stmt
	deleteAllCategoriesForProductByIDStmt          *sql.Stmt
	deleteAllWishListItemsByUserIDStmt             *sql.Stmt
	deleteCategoryByNameStmt                       *sql.Stmt
	deleteProductByIDStmt                          *sql.Stmt
	deleteProductsBySellerIDStmt                   *sql.Stmt
	deleteWishListItemByUserAndProductIDStmt       *sql.Stmt
	editCategoryNameByNameStmt                     *sql.Stmt
	editProductByIDStmt                            *sql.Stmt
	getAllCategoriesStmt                           *sql.Stmt
	getAllCategoriesForAdminStmt                   *sql.Stmt
	getAllProductsStmt                             *sql.Stmt
	getAllProductsForAdminStmt                     *sql.Stmt
	getAllWishListItemsByUserIDStmt                *sql.Stmt
	getAllWishListItemsWithProductNameByUserIDStmt *sql.Stmt
	getCategoryByIDStmt                            *sql.Stmt
	getCategoryByNameStmt                          *sql.Stmt
	getCategoryNamesOfProductByIDStmt              *sql.Stmt
	getProductAndCategoryNameByIDStmt              *sql.Stmt
	getProductAverageRatingAndTotalRatingStmt      *sql.Stmt
	getProductByIDStmt                             *sql.Stmt
	getProductReviewsStmt                          *sql.Stmt
	getProductsByCategoryNameStmt                  *sql.Stmt
	getProductsBySellerIDStmt                      *sql.Stmt
	getReviewByUserAndProductIDStmt                *sql.Stmt
	getWishListItemByUserAndProductIDStmt          *sql.Stmt
	incProductStockByIDStmt                        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                             tx,
		tx:                                             tx,
		addCateogryStmt:                                q.addCateogryStmt,
		addProductStmt:                                 q.addProductStmt,
		addProductReviewWithCommmentStmt:               q.addProductReviewWithCommmentStmt,
		addProductReviewWithoutCommentStmt:             q.addProductReviewWithoutCommentStmt,
		addProductToCategoryByCategoryNameStmt:         q.addProductToCategoryByCategoryNameStmt,
		addProductToCategoryByIDStmt:                   q.addProductToCategoryByIDStmt,
		addWishListItemStmt:                            q.addWishListItemStmt,
		decProductStockByIDStmt:                        q.decProductStockByIDStmt,
		deleteAllCategoriesForProductByIDStmt:          q.deleteAllCategoriesForProductByIDStmt,
		deleteAllWishListItemsByUserIDStmt:             q.deleteAllWishListItemsByUserIDStmt,
		deleteCategoryByNameStmt:                       q.deleteCategoryByNameStmt,
		deleteProductByIDStmt:                          q.deleteProductByIDStmt,
		deleteProductsBySellerIDStmt:                   q.deleteProductsBySellerIDStmt,
		deleteWishListItemByUserAndProductIDStmt:       q.deleteWishListItemByUserAndProductIDStmt,
		editCategoryNameByNameStmt:                     q.editCategoryNameByNameStmt,
		editProductByIDStmt:                            q.editProductByIDStmt,
		getAllCategoriesStmt:                           q.getAllCategoriesStmt,
		getAllCategoriesForAdminStmt:                   q.getAllCategoriesForAdminStmt,
		getAllProductsStmt:                             q.getAllProductsStmt,
		getAllProductsForAdminStmt:                     q.getAllProductsForAdminStmt,
		getAllWishListItemsByUserIDStmt:                q.getAllWishListItemsByUserIDStmt,
		getAllWishListItemsWithProductNameByUserIDStmt: q.getAllWishListItemsWithProductNameByUserIDStmt,
		getCategoryByIDStmt:                            q.getCategoryByIDStmt,
		getCategoryByNameStmt:                          q.getCategoryByNameStmt,
		getCategoryNamesOfProductByIDStmt:              q.getCategoryNamesOfProductByIDStmt,
		getProductAndCategoryNameByIDStmt:              q.getProductAndCategoryNameByIDStmt,
		getProductAverageRatingAndTotalRatingStmt:      q.getProductAverageRatingAndTotalRatingStmt,
		getProductByIDStmt:                             q.getProductByIDStmt,
		getProductReviewsStmt:                          q.getProductReviewsStmt,
		getProductsByCategoryNameStmt:                  q.getProductsByCategoryNameStmt,
		getProductsBySellerIDStmt:                      q.getProductsBySellerIDStmt,
		getReviewByUserAndProductIDStmt:                q.getReviewByUserAndProductIDStmt,
		getWishListItemByUserAndProductIDStmt:          q.getWishListItemByUserAndProductIDStmt,
		incProductStockByIDStmt:                        q.incProductStockByIDStmt,
	}
}
