// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"userId"`
	Type         string    `json:"type"`
	BuildingName string    `json:"buildingName"`
	StreetName   string    `json:"streetName"`
	Town         string    `json:"town"`
	District     string    `json:"district"`
	State        string    `json:"state"`
	Pincode      int32     `json:"pincode"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Category struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	IsDeleted bool      `json:"isDeleted"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type LoginOtp struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	Otp       int32     `json:"otp"`
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type Product struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Price       int32         `json:"price"`
	Stock       int32         `json:"stock"`
	SellerID    uuid.UUID     `json:"sellerId"`
	CategoryID  uuid.NullUUID `json:"categoryId"`
	IsDeleted   bool          `json:"isDeleted"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type ProductImage struct {
	ID        uuid.UUID `json:"id"`
	ProductID uuid.UUID `json:"productId"`
	ImageUrl  string    `json:"imageUrl"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Review struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"userId"`
	ProductID uuid.UUID      `json:"productId"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	IsDeleted bool           `json:"isDeleted"`
	IsEdited  bool           `json:"isEdited"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	IsValid   bool      `json:"isValid"`
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Phone     int64          `json:"phone"`
	Password  string         `json:"password"`
	Role      string         `json:"role"`
	IsBlocked bool           `json:"isBlocked"`
	GstNo     sql.NullString `json:"gstNo"`
	About     sql.NullString `json:"about"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}
