// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addAddressByUserIDStmt, err = db.PrepareContext(ctx, addAddressByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query AddAddressByUserID: %w", err)
	}
	if q.addAndVerifyUserStmt, err = db.PrepareContext(ctx, addAndVerifyUser); err != nil {
		return nil, fmt.Errorf("error preparing query AddAndVerifyUser: %w", err)
	}
	if q.addForgotOTPByUserIDStmt, err = db.PrepareContext(ctx, addForgotOTPByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query AddForgotOTPByUserID: %w", err)
	}
	if q.addOTPStmt, err = db.PrepareContext(ctx, addOTP); err != nil {
		return nil, fmt.Errorf("error preparing query AddOTP: %w", err)
	}
	if q.addSavingsToWalletByUserIDStmt, err = db.PrepareContext(ctx, addSavingsToWalletByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query AddSavingsToWalletByUserID: %w", err)
	}
	if q.addSellerStmt, err = db.PrepareContext(ctx, addSeller); err != nil {
		return nil, fmt.Errorf("error preparing query AddSeller: %w", err)
	}
	if q.addSessionStmt, err = db.PrepareContext(ctx, addSession); err != nil {
		return nil, fmt.Errorf("error preparing query AddSession: %w", err)
	}
	if q.addUserStmt, err = db.PrepareContext(ctx, addUser); err != nil {
		return nil, fmt.Errorf("error preparing query AddUser: %w", err)
	}
	if q.addWalletByUserIDStmt, err = db.PrepareContext(ctx, addWalletByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query AddWalletByUserID: %w", err)
	}
	if q.blockUserByIDStmt, err = db.PrepareContext(ctx, blockUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query BlockUserByID: %w", err)
	}
	if q.changeNameByUserIDStmt, err = db.PrepareContext(ctx, changeNameByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query ChangeNameByUserID: %w", err)
	}
	if q.changePasswordByUserIDStmt, err = db.PrepareContext(ctx, changePasswordByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query ChangePasswordByUserID: %w", err)
	}
	if q.deleteAddressByIDStmt, err = db.PrepareContext(ctx, deleteAddressByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAddressByID: %w", err)
	}
	if q.deleteAddressesByUserIDStmt, err = db.PrepareContext(ctx, deleteAddressesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAddressesByUserID: %w", err)
	}
	if q.deleteForgotOTPByEmailStmt, err = db.PrepareContext(ctx, deleteForgotOTPByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteForgotOTPByEmail: %w", err)
	}
	if q.deleteOTPByEmailStmt, err = db.PrepareContext(ctx, deleteOTPByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOTPByEmail: %w", err)
	}
	if q.deleteSessionByIDStmt, err = db.PrepareContext(ctx, deleteSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionByID: %w", err)
	}
	if q.deleteSessionsByuserIDStmt, err = db.PrepareContext(ctx, deleteSessionsByuserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionsByuserID: %w", err)
	}
	if q.editAddressByIDStmt, err = db.PrepareContext(ctx, editAddressByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditAddressByID: %w", err)
	}
	if q.editSellerByIDStmt, err = db.PrepareContext(ctx, editSellerByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditSellerByID: %w", err)
	}
	if q.editUserByIDStmt, err = db.PrepareContext(ctx, editUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditUserByID: %w", err)
	}
	if q.getAddressByIDStmt, err = db.PrepareContext(ctx, getAddressByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAddressByID: %w", err)
	}
	if q.getAddressBySellerIDStmt, err = db.PrepareContext(ctx, getAddressBySellerID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAddressBySellerID: %w", err)
	}
	if q.getAddressesByUserIDStmt, err = db.PrepareContext(ctx, getAddressesByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAddressesByUserID: %w", err)
	}
	if q.getAllSessionsByUserIDStmt, err = db.PrepareContext(ctx, getAllSessionsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllSessionsByUserID: %w", err)
	}
	if q.getAllUsersStmt, err = db.PrepareContext(ctx, getAllUsers); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsers: %w", err)
	}
	if q.getAllUsersByRoleSellerStmt, err = db.PrepareContext(ctx, getAllUsersByRoleSeller); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsersByRoleSeller: %w", err)
	}
	if q.getAllUsersByRoleUserStmt, err = db.PrepareContext(ctx, getAllUsersByRoleUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUsersByRoleUser: %w", err)
	}
	if q.getSessionDetailsByIDStmt, err = db.PrepareContext(ctx, getSessionDetailsByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionDetailsByID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIdStmt, err = db.PrepareContext(ctx, getUserById); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserById: %w", err)
	}
	if q.getUserBySessionIDStmt, err = db.PrepareContext(ctx, getUserBySessionID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserBySessionID: %w", err)
	}
	if q.getUserWithPasswordByEmailStmt, err = db.PrepareContext(ctx, getUserWithPasswordByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserWithPasswordByEmail: %w", err)
	}
	if q.getValidForgotOTPByUserIDStmt, err = db.PrepareContext(ctx, getValidForgotOTPByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetValidForgotOTPByUserID: %w", err)
	}
	if q.getValidOTPByUserIDStmt, err = db.PrepareContext(ctx, getValidOTPByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetValidOTPByUserID: %w", err)
	}
	if q.getWalletByUserIDStmt, err = db.PrepareContext(ctx, getWalletByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetWalletByUserID: %w", err)
	}
	if q.retractSavingsFromWalletByUserIDStmt, err = db.PrepareContext(ctx, retractSavingsFromWalletByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query RetractSavingsFromWalletByUserID: %w", err)
	}
	if q.unblockUserByIDStmt, err = db.PrepareContext(ctx, unblockUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query UnblockUserByID: %w", err)
	}
	if q.verifySellerByIDStmt, err = db.PrepareContext(ctx, verifySellerByID); err != nil {
		return nil, fmt.Errorf("error preparing query VerifySellerByID: %w", err)
	}
	if q.verifySellerEmailByIDStmt, err = db.PrepareContext(ctx, verifySellerEmailByID); err != nil {
		return nil, fmt.Errorf("error preparing query VerifySellerEmailByID: %w", err)
	}
	if q.verifyUserByIDStmt, err = db.PrepareContext(ctx, verifyUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query VerifyUserByID: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addAddressByUserIDStmt != nil {
		if cerr := q.addAddressByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addAddressByUserIDStmt: %w", cerr)
		}
	}
	if q.addAndVerifyUserStmt != nil {
		if cerr := q.addAndVerifyUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addAndVerifyUserStmt: %w", cerr)
		}
	}
	if q.addForgotOTPByUserIDStmt != nil {
		if cerr := q.addForgotOTPByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addForgotOTPByUserIDStmt: %w", cerr)
		}
	}
	if q.addOTPStmt != nil {
		if cerr := q.addOTPStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addOTPStmt: %w", cerr)
		}
	}
	if q.addSavingsToWalletByUserIDStmt != nil {
		if cerr := q.addSavingsToWalletByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addSavingsToWalletByUserIDStmt: %w", cerr)
		}
	}
	if q.addSellerStmt != nil {
		if cerr := q.addSellerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addSellerStmt: %w", cerr)
		}
	}
	if q.addSessionStmt != nil {
		if cerr := q.addSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addSessionStmt: %w", cerr)
		}
	}
	if q.addUserStmt != nil {
		if cerr := q.addUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addUserStmt: %w", cerr)
		}
	}
	if q.addWalletByUserIDStmt != nil {
		if cerr := q.addWalletByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addWalletByUserIDStmt: %w", cerr)
		}
	}
	if q.blockUserByIDStmt != nil {
		if cerr := q.blockUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing blockUserByIDStmt: %w", cerr)
		}
	}
	if q.changeNameByUserIDStmt != nil {
		if cerr := q.changeNameByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing changeNameByUserIDStmt: %w", cerr)
		}
	}
	if q.changePasswordByUserIDStmt != nil {
		if cerr := q.changePasswordByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing changePasswordByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteAddressByIDStmt != nil {
		if cerr := q.deleteAddressByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAddressByIDStmt: %w", cerr)
		}
	}
	if q.deleteAddressesByUserIDStmt != nil {
		if cerr := q.deleteAddressesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAddressesByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteForgotOTPByEmailStmt != nil {
		if cerr := q.deleteForgotOTPByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteForgotOTPByEmailStmt: %w", cerr)
		}
	}
	if q.deleteOTPByEmailStmt != nil {
		if cerr := q.deleteOTPByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOTPByEmailStmt: %w", cerr)
		}
	}
	if q.deleteSessionByIDStmt != nil {
		if cerr := q.deleteSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionByIDStmt: %w", cerr)
		}
	}
	if q.deleteSessionsByuserIDStmt != nil {
		if cerr := q.deleteSessionsByuserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionsByuserIDStmt: %w", cerr)
		}
	}
	if q.editAddressByIDStmt != nil {
		if cerr := q.editAddressByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editAddressByIDStmt: %w", cerr)
		}
	}
	if q.editSellerByIDStmt != nil {
		if cerr := q.editSellerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editSellerByIDStmt: %w", cerr)
		}
	}
	if q.editUserByIDStmt != nil {
		if cerr := q.editUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editUserByIDStmt: %w", cerr)
		}
	}
	if q.getAddressByIDStmt != nil {
		if cerr := q.getAddressByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAddressByIDStmt: %w", cerr)
		}
	}
	if q.getAddressBySellerIDStmt != nil {
		if cerr := q.getAddressBySellerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAddressBySellerIDStmt: %w", cerr)
		}
	}
	if q.getAddressesByUserIDStmt != nil {
		if cerr := q.getAddressesByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAddressesByUserIDStmt: %w", cerr)
		}
	}
	if q.getAllSessionsByUserIDStmt != nil {
		if cerr := q.getAllSessionsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllSessionsByUserIDStmt: %w", cerr)
		}
	}
	if q.getAllUsersStmt != nil {
		if cerr := q.getAllUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersStmt: %w", cerr)
		}
	}
	if q.getAllUsersByRoleSellerStmt != nil {
		if cerr := q.getAllUsersByRoleSellerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersByRoleSellerStmt: %w", cerr)
		}
	}
	if q.getAllUsersByRoleUserStmt != nil {
		if cerr := q.getAllUsersByRoleUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUsersByRoleUserStmt: %w", cerr)
		}
	}
	if q.getSessionDetailsByIDStmt != nil {
		if cerr := q.getSessionDetailsByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionDetailsByIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIdStmt != nil {
		if cerr := q.getUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIdStmt: %w", cerr)
		}
	}
	if q.getUserBySessionIDStmt != nil {
		if cerr := q.getUserBySessionIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserBySessionIDStmt: %w", cerr)
		}
	}
	if q.getUserWithPasswordByEmailStmt != nil {
		if cerr := q.getUserWithPasswordByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserWithPasswordByEmailStmt: %w", cerr)
		}
	}
	if q.getValidForgotOTPByUserIDStmt != nil {
		if cerr := q.getValidForgotOTPByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getValidForgotOTPByUserIDStmt: %w", cerr)
		}
	}
	if q.getValidOTPByUserIDStmt != nil {
		if cerr := q.getValidOTPByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getValidOTPByUserIDStmt: %w", cerr)
		}
	}
	if q.getWalletByUserIDStmt != nil {
		if cerr := q.getWalletByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWalletByUserIDStmt: %w", cerr)
		}
	}
	if q.retractSavingsFromWalletByUserIDStmt != nil {
		if cerr := q.retractSavingsFromWalletByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing retractSavingsFromWalletByUserIDStmt: %w", cerr)
		}
	}
	if q.unblockUserByIDStmt != nil {
		if cerr := q.unblockUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unblockUserByIDStmt: %w", cerr)
		}
	}
	if q.verifySellerByIDStmt != nil {
		if cerr := q.verifySellerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing verifySellerByIDStmt: %w", cerr)
		}
	}
	if q.verifySellerEmailByIDStmt != nil {
		if cerr := q.verifySellerEmailByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing verifySellerEmailByIDStmt: %w", cerr)
		}
	}
	if q.verifyUserByIDStmt != nil {
		if cerr := q.verifyUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing verifyUserByIDStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	addAddressByUserIDStmt               *sql.Stmt
	addAndVerifyUserStmt                 *sql.Stmt
	addForgotOTPByUserIDStmt             *sql.Stmt
	addOTPStmt                           *sql.Stmt
	addSavingsToWalletByUserIDStmt       *sql.Stmt
	addSellerStmt                        *sql.Stmt
	addSessionStmt                       *sql.Stmt
	addUserStmt                          *sql.Stmt
	addWalletByUserIDStmt                *sql.Stmt
	blockUserByIDStmt                    *sql.Stmt
	changeNameByUserIDStmt               *sql.Stmt
	changePasswordByUserIDStmt           *sql.Stmt
	deleteAddressByIDStmt                *sql.Stmt
	deleteAddressesByUserIDStmt          *sql.Stmt
	deleteForgotOTPByEmailStmt           *sql.Stmt
	deleteOTPByEmailStmt                 *sql.Stmt
	deleteSessionByIDStmt                *sql.Stmt
	deleteSessionsByuserIDStmt           *sql.Stmt
	editAddressByIDStmt                  *sql.Stmt
	editSellerByIDStmt                   *sql.Stmt
	editUserByIDStmt                     *sql.Stmt
	getAddressByIDStmt                   *sql.Stmt
	getAddressBySellerIDStmt             *sql.Stmt
	getAddressesByUserIDStmt             *sql.Stmt
	getAllSessionsByUserIDStmt           *sql.Stmt
	getAllUsersStmt                      *sql.Stmt
	getAllUsersByRoleSellerStmt          *sql.Stmt
	getAllUsersByRoleUserStmt            *sql.Stmt
	getSessionDetailsByIDStmt            *sql.Stmt
	getUserByEmailStmt                   *sql.Stmt
	getUserByIdStmt                      *sql.Stmt
	getUserBySessionIDStmt               *sql.Stmt
	getUserWithPasswordByEmailStmt       *sql.Stmt
	getValidForgotOTPByUserIDStmt        *sql.Stmt
	getValidOTPByUserIDStmt              *sql.Stmt
	getWalletByUserIDStmt                *sql.Stmt
	retractSavingsFromWalletByUserIDStmt *sql.Stmt
	unblockUserByIDStmt                  *sql.Stmt
	verifySellerByIDStmt                 *sql.Stmt
	verifySellerEmailByIDStmt            *sql.Stmt
	verifyUserByIDStmt                   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		addAddressByUserIDStmt:               q.addAddressByUserIDStmt,
		addAndVerifyUserStmt:                 q.addAndVerifyUserStmt,
		addForgotOTPByUserIDStmt:             q.addForgotOTPByUserIDStmt,
		addOTPStmt:                           q.addOTPStmt,
		addSavingsToWalletByUserIDStmt:       q.addSavingsToWalletByUserIDStmt,
		addSellerStmt:                        q.addSellerStmt,
		addSessionStmt:                       q.addSessionStmt,
		addUserStmt:                          q.addUserStmt,
		addWalletByUserIDStmt:                q.addWalletByUserIDStmt,
		blockUserByIDStmt:                    q.blockUserByIDStmt,
		changeNameByUserIDStmt:               q.changeNameByUserIDStmt,
		changePasswordByUserIDStmt:           q.changePasswordByUserIDStmt,
		deleteAddressByIDStmt:                q.deleteAddressByIDStmt,
		deleteAddressesByUserIDStmt:          q.deleteAddressesByUserIDStmt,
		deleteForgotOTPByEmailStmt:           q.deleteForgotOTPByEmailStmt,
		deleteOTPByEmailStmt:                 q.deleteOTPByEmailStmt,
		deleteSessionByIDStmt:                q.deleteSessionByIDStmt,
		deleteSessionsByuserIDStmt:           q.deleteSessionsByuserIDStmt,
		editAddressByIDStmt:                  q.editAddressByIDStmt,
		editSellerByIDStmt:                   q.editSellerByIDStmt,
		editUserByIDStmt:                     q.editUserByIDStmt,
		getAddressByIDStmt:                   q.getAddressByIDStmt,
		getAddressBySellerIDStmt:             q.getAddressBySellerIDStmt,
		getAddressesByUserIDStmt:             q.getAddressesByUserIDStmt,
		getAllSessionsByUserIDStmt:           q.getAllSessionsByUserIDStmt,
		getAllUsersStmt:                      q.getAllUsersStmt,
		getAllUsersByRoleSellerStmt:          q.getAllUsersByRoleSellerStmt,
		getAllUsersByRoleUserStmt:            q.getAllUsersByRoleUserStmt,
		getSessionDetailsByIDStmt:            q.getSessionDetailsByIDStmt,
		getUserByEmailStmt:                   q.getUserByEmailStmt,
		getUserByIdStmt:                      q.getUserByIdStmt,
		getUserBySessionIDStmt:               q.getUserBySessionIDStmt,
		getUserWithPasswordByEmailStmt:       q.getUserWithPasswordByEmailStmt,
		getValidForgotOTPByUserIDStmt:        q.getValidForgotOTPByUserIDStmt,
		getValidOTPByUserIDStmt:              q.getValidOTPByUserIDStmt,
		getWalletByUserIDStmt:                q.getWalletByUserIDStmt,
		retractSavingsFromWalletByUserIDStmt: q.retractSavingsFromWalletByUserIDStmt,
		unblockUserByIDStmt:                  q.unblockUserByIDStmt,
		verifySellerByIDStmt:                 q.verifySellerByIDStmt,
		verifySellerEmailByIDStmt:            q.verifySellerEmailByIDStmt,
		verifyUserByIDStmt:                   q.verifyUserByIDStmt,
	}
}
