// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: userpb.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserBySessionIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBySessionIDRequest) Reset() {
	*x = GetUserBySessionIDRequest{}
	mi := &file_userpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBySessionIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBySessionIDRequest) ProtoMessage() {}

func (x *GetUserBySessionIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBySessionIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserBySessionIDRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserBySessionIDRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type GetUserBySessionIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBySessionIDResponse) Reset() {
	*x = GetUserBySessionIDResponse{}
	mi := &file_userpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBySessionIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBySessionIDResponse) ProtoMessage() {}

func (x *GetUserBySessionIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBySessionIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserBySessionIDResponse) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserBySessionIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserBySessionIDResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserBySessionIDResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserBySessionIDResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserBySessionIDResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type GetAddressBySellerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerID      string                 `protobuf:"bytes,1,opt,name=sellerID,proto3" json:"sellerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressBySellerIDRequest) Reset() {
	*x = GetAddressBySellerIDRequest{}
	mi := &file_userpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressBySellerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressBySellerIDRequest) ProtoMessage() {}

func (x *GetAddressBySellerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressBySellerIDRequest.ProtoReflect.Descriptor instead.
func (*GetAddressBySellerIDRequest) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddressBySellerIDRequest) GetSellerID() string {
	if x != nil {
		return x.SellerID
	}
	return ""
}

type GetAddressBySellerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressBySellerIDResponse) Reset() {
	*x = GetAddressBySellerIDResponse{}
	mi := &file_userpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressBySellerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressBySellerIDResponse) ProtoMessage() {}

func (x *GetAddressBySellerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressBySellerIDResponse.ProtoReflect.Descriptor instead.
func (*GetAddressBySellerIDResponse) Descriptor() ([]byte, []int) {
	return file_userpb_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddressBySellerIDResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_userpb_proto protoreflect.FileDescriptor

const file_userpb_proto_rawDesc = "" +
	"\n" +
	"\fuserpb.proto\x12\x06userpb\"9\n" +
	"\x19GetUserBySessionIDRequest\x12\x1c\n" +
	"\tsessionID\x18\x01 \x01(\tR\tsessionID\"\x80\x01\n" +
	"\x1aGetUserBySessionIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\"9\n" +
	"\x1bGetAddressBySellerIDRequest\x12\x1a\n" +
	"\bsellerID\x18\x01 \x01(\tR\bsellerID\"6\n" +
	"\x1cGetAddressBySellerIDResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\xcd\x01\n" +
	"\vUserService\x12[\n" +
	"\x12GetUserBySessionID\x12!.userpb.GetUserBySessionIDRequest\x1a\".userpb.GetUserBySessionIDResponse\x12a\n" +
	"\x14GetAddressBySellerID\x12#.userpb.GetAddressBySellerIDRequest\x1a$.userpb.GetAddressBySellerIDResponseB5Z3github.com/amankhys/brocamp/ecom/pkg/pb/user/userpbb\x06proto3"

var (
	file_userpb_proto_rawDescOnce sync.Once
	file_userpb_proto_rawDescData []byte
)

func file_userpb_proto_rawDescGZIP() []byte {
	file_userpb_proto_rawDescOnce.Do(func() {
		file_userpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userpb_proto_rawDesc), len(file_userpb_proto_rawDesc)))
	})
	return file_userpb_proto_rawDescData
}

var file_userpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userpb_proto_goTypes = []any{
	(*GetUserBySessionIDRequest)(nil),    // 0: userpb.GetUserBySessionIDRequest
	(*GetUserBySessionIDResponse)(nil),   // 1: userpb.GetUserBySessionIDResponse
	(*GetAddressBySellerIDRequest)(nil),  // 2: userpb.GetAddressBySellerIDRequest
	(*GetAddressBySellerIDResponse)(nil), // 3: userpb.GetAddressBySellerIDResponse
}
var file_userpb_proto_depIdxs = []int32{
	0, // 0: userpb.UserService.GetUserBySessionID:input_type -> userpb.GetUserBySessionIDRequest
	2, // 1: userpb.UserService.GetAddressBySellerID:input_type -> userpb.GetAddressBySellerIDRequest
	1, // 2: userpb.UserService.GetUserBySessionID:output_type -> userpb.GetUserBySessionIDResponse
	3, // 3: userpb.UserService.GetAddressBySellerID:output_type -> userpb.GetAddressBySellerIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userpb_proto_init() }
func file_userpb_proto_init() {
	if File_userpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userpb_proto_rawDesc), len(file_userpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userpb_proto_goTypes,
		DependencyIndexes: file_userpb_proto_depIdxs,
		MessageInfos:      file_userpb_proto_msgTypes,
	}.Build()
	File_userpb_proto = out.File
	file_userpb_proto_goTypes = nil
	file_userpb_proto_depIdxs = nil
}
