// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCartItemStmt, err = db.PrepareContext(ctx, addCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddCartItem: %w", err)
	}
	if q.addCouponStmt, err = db.PrepareContext(ctx, addCoupon); err != nil {
		return nil, fmt.Errorf("error preparing query AddCoupon: %w", err)
	}
	if q.addOrderStmt, err = db.PrepareContext(ctx, addOrder); err != nil {
		return nil, fmt.Errorf("error preparing query AddOrder: %w", err)
	}
	if q.addOrderITemStmt, err = db.PrepareContext(ctx, addOrderITem); err != nil {
		return nil, fmt.Errorf("error preparing query AddOrderITem: %w", err)
	}
	if q.addPaymentStmt, err = db.PrepareContext(ctx, addPayment); err != nil {
		return nil, fmt.Errorf("error preparing query AddPayment: %w", err)
	}
	if q.addShippingAddressStmt, err = db.PrepareContext(ctx, addShippingAddress); err != nil {
		return nil, fmt.Errorf("error preparing query AddShippingAddress: %w", err)
	}
	if q.addVendorPaymentStmt, err = db.PrepareContext(ctx, addVendorPayment); err != nil {
		return nil, fmt.Errorf("error preparing query AddVendorPayment: %w", err)
	}
	if q.cancelOrderByIDStmt, err = db.PrepareContext(ctx, cancelOrderByID); err != nil {
		return nil, fmt.Errorf("error preparing query CancelOrderByID: %w", err)
	}
	if q.cancelPaymentByOrderIDStmt, err = db.PrepareContext(ctx, cancelPaymentByOrderID); err != nil {
		return nil, fmt.Errorf("error preparing query CancelPaymentByOrderID: %w", err)
	}
	if q.cancelVendorPaymentByOrderItemIDStmt, err = db.PrepareContext(ctx, cancelVendorPaymentByOrderItemID); err != nil {
		return nil, fmt.Errorf("error preparing query CancelVendorPaymentByOrderItemID: %w", err)
	}
	if q.cancelVendorPaymentsByOrderIDStmt, err = db.PrepareContext(ctx, cancelVendorPaymentsByOrderID); err != nil {
		return nil, fmt.Errorf("error preparing query CancelVendorPaymentsByOrderID: %w", err)
	}
	if q.changeOrderItemStatusByIDStmt, err = db.PrepareContext(ctx, changeOrderItemStatusByID); err != nil {
		return nil, fmt.Errorf("error preparing query ChangeOrderItemStatusByID: %w", err)
	}
	if q.decPaymentAmountByOrderItemIDStmt, err = db.PrepareContext(ctx, decPaymentAmountByOrderItemID); err != nil {
		return nil, fmt.Errorf("error preparing query DecPaymentAmountByOrderItemID: %w", err)
	}
	if q.deleteCartItemByUserIDAndProductIDStmt, err = db.PrepareContext(ctx, deleteCartItemByUserIDAndProductID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCartItemByUserIDAndProductID: %w", err)
	}
	if q.deleteCartItemsByUserIDStmt, err = db.PrepareContext(ctx, deleteCartItemsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCartItemsByUserID: %w", err)
	}
	if q.deleteCouponByIDStmt, err = db.PrepareContext(ctx, deleteCouponByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCouponByID: %w", err)
	}
	if q.deleteCouponByNameStmt, err = db.PrepareContext(ctx, deleteCouponByName); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCouponByName: %w", err)
	}
	if q.deleteOrderByIDStmt, err = db.PrepareContext(ctx, deleteOrderByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOrderByID: %w", err)
	}
	if q.editCartItemByIDStmt, err = db.PrepareContext(ctx, editCartItemByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditCartItemByID: %w", err)
	}
	if q.editCouponByIDStmt, err = db.PrepareContext(ctx, editCouponByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditCouponByID: %w", err)
	}
	if q.editCouponByNameStmt, err = db.PrepareContext(ctx, editCouponByName); err != nil {
		return nil, fmt.Errorf("error preparing query EditCouponByName: %w", err)
	}
	if q.editOrderAmountByIDStmt, err = db.PrepareContext(ctx, editOrderAmountByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditOrderAmountByID: %w", err)
	}
	if q.editOrderItemStatusByIDStmt, err = db.PrepareContext(ctx, editOrderItemStatusByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditOrderItemStatusByID: %w", err)
	}
	if q.editPaymentByOrderIDStmt, err = db.PrepareContext(ctx, editPaymentByOrderID); err != nil {
		return nil, fmt.Errorf("error preparing query EditPaymentByOrderID: %w", err)
	}
	if q.editPaymentStatusByIDStmt, err = db.PrepareContext(ctx, editPaymentStatusByID); err != nil {
		return nil, fmt.Errorf("error preparing query EditPaymentStatusByID: %w", err)
	}
	if q.editPaymentStatusByOrderIDStmt, err = db.PrepareContext(ctx, editPaymentStatusByOrderID); err != nil {
		return nil, fmt.Errorf("error preparing query EditPaymentStatusByOrderID: %w", err)
	}
	if q.editVendorPaymentStatusByOrderItemIDStmt, err = db.PrepareContext(ctx, editVendorPaymentStatusByOrderItemID); err != nil {
		return nil, fmt.Errorf("error preparing query EditVendorPaymentStatusByOrderItemID: %w", err)
	}
	if q.getAllCouponsStmt, err = db.PrepareContext(ctx, getAllCoupons); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllCoupons: %w", err)
	}
	if q.getAllCouponsForAdminStmt, err = db.PrepareContext(ctx, getAllCouponsForAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllCouponsForAdmin: %w", err)
	}
	if q.getAllOrderItemsForAdminStmt, err = db.PrepareContext(ctx, getAllOrderItemsForAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllOrderItemsForAdmin: %w", err)
	}
	if q.getAllOrdersStmt, err = db.PrepareContext(ctx, getAllOrders); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllOrders: %w", err)
	}
	if q.getCartItemByIDStmt, err = db.PrepareContext(ctx, getCartItemByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartItemByID: %w", err)
	}
	if q.getCartItemByUserIDAndProductIDStmt, err = db.PrepareContext(ctx, getCartItemByUserIDAndProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartItemByUserIDAndProductID: %w", err)
	}
	if q.getCartItemsByUserIDStmt, err = db.PrepareContext(ctx, getCartItemsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartItemsByUserID: %w", err)
	}
	if q.getCouponByIDStmt, err = db.PrepareContext(ctx, getCouponByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCouponByID: %w", err)
	}
	if q.getCouponByNameStmt, err = db.PrepareContext(ctx, getCouponByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetCouponByName: %w", err)
	}
	if q.getOrderByIDStmt, err = db.PrepareContext(ctx, getOrderByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderByID: %w", err)
	}
	if q.getOrderItemByIDStmt, err = db.PrepareContext(ctx, getOrderItemByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItemByID: %w", err)
	}
	if q.getOrderItemByUserAndProductIDStmt, err = db.PrepareContext(ctx, getOrderItemByUserAndProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItemByUserAndProductID: %w", err)
	}
	if q.getOrderItemsByOrderIDStmt, err = db.PrepareContext(ctx, getOrderItemsByOrderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItemsByOrderID: %w", err)
	}
	if q.getOrderItemsBySellerIDStmt, err = db.PrepareContext(ctx, getOrderItemsBySellerID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItemsBySellerID: %w", err)
	}
	if q.getOrderItemsBySellerIDAndDateRangeStmt, err = db.PrepareContext(ctx, getOrderItemsBySellerIDAndDateRange); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItemsBySellerIDAndDateRange: %w", err)
	}
	if q.getOrderItemsByUserIDStmt, err = db.PrepareContext(ctx, getOrderItemsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItemsByUserID: %w", err)
	}
	if q.getOrdersByUserIDStmt, err = db.PrepareContext(ctx, getOrdersByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrdersByUserID: %w", err)
	}
	if q.getPaymentByOrderIDStmt, err = db.PrepareContext(ctx, getPaymentByOrderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaymentByOrderID: %w", err)
	}
	if q.getProductFromCartByIDStmt, err = db.PrepareContext(ctx, getProductFromCartByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductFromCartByID: %w", err)
	}
	if q.getProductNameAndQuantityFromCartsByIDStmt, err = db.PrepareContext(ctx, getProductNameAndQuantityFromCartsByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductNameAndQuantityFromCartsByID: %w", err)
	}
	if q.getReviewByUserAndProductIDStmt, err = db.PrepareContext(ctx, getReviewByUserAndProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReviewByUserAndProductID: %w", err)
	}
	if q.getSellerIDFromOrderItemIDStmt, err = db.PrepareContext(ctx, getSellerIDFromOrderItemID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSellerIDFromOrderItemID: %w", err)
	}
	if q.getShippingAddressByOrderIDStmt, err = db.PrepareContext(ctx, getShippingAddressByOrderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetShippingAddressByOrderID: %w", err)
	}
	if q.getSumOfCartItemsByUserIDStmt, err = db.PrepareContext(ctx, getSumOfCartItemsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSumOfCartItemsByUserID: %w", err)
	}
	if q.getTotalAmountOfCartItemsStmt, err = db.PrepareContext(ctx, getTotalAmountOfCartItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalAmountOfCartItems: %w", err)
	}
	if q.getUserIDFromOrderItemIDStmt, err = db.PrepareContext(ctx, getUserIDFromOrderItemID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserIDFromOrderItemID: %w", err)
	}
	if q.getValidCouponByNameStmt, err = db.PrepareContext(ctx, getValidCouponByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetValidCouponByName: %w", err)
	}
	if q.getVendorPaymentByOrderItemIDStmt, err = db.PrepareContext(ctx, getVendorPaymentByOrderItemID); err != nil {
		return nil, fmt.Errorf("error preparing query GetVendorPaymentByOrderItemID: %w", err)
	}
	if q.getVendorPaymentsByDateRangeStmt, err = db.PrepareContext(ctx, getVendorPaymentsByDateRange); err != nil {
		return nil, fmt.Errorf("error preparing query GetVendorPaymentsByDateRange: %w", err)
	}
	if q.getVendorPaymentsBySellerIDStmt, err = db.PrepareContext(ctx, getVendorPaymentsBySellerID); err != nil {
		return nil, fmt.Errorf("error preparing query GetVendorPaymentsBySellerID: %w", err)
	}
	if q.getVendorPaymentsBySellerIDAndDateRangeStmt, err = db.PrepareContext(ctx, getVendorPaymentsBySellerIDAndDateRange); err != nil {
		return nil, fmt.Errorf("error preparing query GetVendorPaymentsBySellerIDAndDateRange: %w", err)
	}
	if q.updateOrderTotalAmountStmt, err = db.PrepareContext(ctx, updateOrderTotalAmount); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderTotalAmount: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCartItemStmt != nil {
		if cerr := q.addCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCartItemStmt: %w", cerr)
		}
	}
	if q.addCouponStmt != nil {
		if cerr := q.addCouponStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCouponStmt: %w", cerr)
		}
	}
	if q.addOrderStmt != nil {
		if cerr := q.addOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addOrderStmt: %w", cerr)
		}
	}
	if q.addOrderITemStmt != nil {
		if cerr := q.addOrderITemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addOrderITemStmt: %w", cerr)
		}
	}
	if q.addPaymentStmt != nil {
		if cerr := q.addPaymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addPaymentStmt: %w", cerr)
		}
	}
	if q.addShippingAddressStmt != nil {
		if cerr := q.addShippingAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addShippingAddressStmt: %w", cerr)
		}
	}
	if q.addVendorPaymentStmt != nil {
		if cerr := q.addVendorPaymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addVendorPaymentStmt: %w", cerr)
		}
	}
	if q.cancelOrderByIDStmt != nil {
		if cerr := q.cancelOrderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelOrderByIDStmt: %w", cerr)
		}
	}
	if q.cancelPaymentByOrderIDStmt != nil {
		if cerr := q.cancelPaymentByOrderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelPaymentByOrderIDStmt: %w", cerr)
		}
	}
	if q.cancelVendorPaymentByOrderItemIDStmt != nil {
		if cerr := q.cancelVendorPaymentByOrderItemIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelVendorPaymentByOrderItemIDStmt: %w", cerr)
		}
	}
	if q.cancelVendorPaymentsByOrderIDStmt != nil {
		if cerr := q.cancelVendorPaymentsByOrderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing cancelVendorPaymentsByOrderIDStmt: %w", cerr)
		}
	}
	if q.changeOrderItemStatusByIDStmt != nil {
		if cerr := q.changeOrderItemStatusByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing changeOrderItemStatusByIDStmt: %w", cerr)
		}
	}
	if q.decPaymentAmountByOrderItemIDStmt != nil {
		if cerr := q.decPaymentAmountByOrderItemIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing decPaymentAmountByOrderItemIDStmt: %w", cerr)
		}
	}
	if q.deleteCartItemByUserIDAndProductIDStmt != nil {
		if cerr := q.deleteCartItemByUserIDAndProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCartItemByUserIDAndProductIDStmt: %w", cerr)
		}
	}
	if q.deleteCartItemsByUserIDStmt != nil {
		if cerr := q.deleteCartItemsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCartItemsByUserIDStmt: %w", cerr)
		}
	}
	if q.deleteCouponByIDStmt != nil {
		if cerr := q.deleteCouponByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCouponByIDStmt: %w", cerr)
		}
	}
	if q.deleteCouponByNameStmt != nil {
		if cerr := q.deleteCouponByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCouponByNameStmt: %w", cerr)
		}
	}
	if q.deleteOrderByIDStmt != nil {
		if cerr := q.deleteOrderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOrderByIDStmt: %w", cerr)
		}
	}
	if q.editCartItemByIDStmt != nil {
		if cerr := q.editCartItemByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editCartItemByIDStmt: %w", cerr)
		}
	}
	if q.editCouponByIDStmt != nil {
		if cerr := q.editCouponByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editCouponByIDStmt: %w", cerr)
		}
	}
	if q.editCouponByNameStmt != nil {
		if cerr := q.editCouponByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editCouponByNameStmt: %w", cerr)
		}
	}
	if q.editOrderAmountByIDStmt != nil {
		if cerr := q.editOrderAmountByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editOrderAmountByIDStmt: %w", cerr)
		}
	}
	if q.editOrderItemStatusByIDStmt != nil {
		if cerr := q.editOrderItemStatusByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editOrderItemStatusByIDStmt: %w", cerr)
		}
	}
	if q.editPaymentByOrderIDStmt != nil {
		if cerr := q.editPaymentByOrderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editPaymentByOrderIDStmt: %w", cerr)
		}
	}
	if q.editPaymentStatusByIDStmt != nil {
		if cerr := q.editPaymentStatusByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editPaymentStatusByIDStmt: %w", cerr)
		}
	}
	if q.editPaymentStatusByOrderIDStmt != nil {
		if cerr := q.editPaymentStatusByOrderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editPaymentStatusByOrderIDStmt: %w", cerr)
		}
	}
	if q.editVendorPaymentStatusByOrderItemIDStmt != nil {
		if cerr := q.editVendorPaymentStatusByOrderItemIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing editVendorPaymentStatusByOrderItemIDStmt: %w", cerr)
		}
	}
	if q.getAllCouponsStmt != nil {
		if cerr := q.getAllCouponsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllCouponsStmt: %w", cerr)
		}
	}
	if q.getAllCouponsForAdminStmt != nil {
		if cerr := q.getAllCouponsForAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllCouponsForAdminStmt: %w", cerr)
		}
	}
	if q.getAllOrderItemsForAdminStmt != nil {
		if cerr := q.getAllOrderItemsForAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllOrderItemsForAdminStmt: %w", cerr)
		}
	}
	if q.getAllOrdersStmt != nil {
		if cerr := q.getAllOrdersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllOrdersStmt: %w", cerr)
		}
	}
	if q.getCartItemByIDStmt != nil {
		if cerr := q.getCartItemByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartItemByIDStmt: %w", cerr)
		}
	}
	if q.getCartItemByUserIDAndProductIDStmt != nil {
		if cerr := q.getCartItemByUserIDAndProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartItemByUserIDAndProductIDStmt: %w", cerr)
		}
	}
	if q.getCartItemsByUserIDStmt != nil {
		if cerr := q.getCartItemsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartItemsByUserIDStmt: %w", cerr)
		}
	}
	if q.getCouponByIDStmt != nil {
		if cerr := q.getCouponByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCouponByIDStmt: %w", cerr)
		}
	}
	if q.getCouponByNameStmt != nil {
		if cerr := q.getCouponByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCouponByNameStmt: %w", cerr)
		}
	}
	if q.getOrderByIDStmt != nil {
		if cerr := q.getOrderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderByIDStmt: %w", cerr)
		}
	}
	if q.getOrderItemByIDStmt != nil {
		if cerr := q.getOrderItemByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemByIDStmt: %w", cerr)
		}
	}
	if q.getOrderItemByUserAndProductIDStmt != nil {
		if cerr := q.getOrderItemByUserAndProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemByUserAndProductIDStmt: %w", cerr)
		}
	}
	if q.getOrderItemsByOrderIDStmt != nil {
		if cerr := q.getOrderItemsByOrderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemsByOrderIDStmt: %w", cerr)
		}
	}
	if q.getOrderItemsBySellerIDStmt != nil {
		if cerr := q.getOrderItemsBySellerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemsBySellerIDStmt: %w", cerr)
		}
	}
	if q.getOrderItemsBySellerIDAndDateRangeStmt != nil {
		if cerr := q.getOrderItemsBySellerIDAndDateRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemsBySellerIDAndDateRangeStmt: %w", cerr)
		}
	}
	if q.getOrderItemsByUserIDStmt != nil {
		if cerr := q.getOrderItemsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemsByUserIDStmt: %w", cerr)
		}
	}
	if q.getOrdersByUserIDStmt != nil {
		if cerr := q.getOrdersByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrdersByUserIDStmt: %w", cerr)
		}
	}
	if q.getPaymentByOrderIDStmt != nil {
		if cerr := q.getPaymentByOrderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaymentByOrderIDStmt: %w", cerr)
		}
	}
	if q.getProductFromCartByIDStmt != nil {
		if cerr := q.getProductFromCartByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductFromCartByIDStmt: %w", cerr)
		}
	}
	if q.getProductNameAndQuantityFromCartsByIDStmt != nil {
		if cerr := q.getProductNameAndQuantityFromCartsByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductNameAndQuantityFromCartsByIDStmt: %w", cerr)
		}
	}
	if q.getReviewByUserAndProductIDStmt != nil {
		if cerr := q.getReviewByUserAndProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReviewByUserAndProductIDStmt: %w", cerr)
		}
	}
	if q.getSellerIDFromOrderItemIDStmt != nil {
		if cerr := q.getSellerIDFromOrderItemIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSellerIDFromOrderItemIDStmt: %w", cerr)
		}
	}
	if q.getShippingAddressByOrderIDStmt != nil {
		if cerr := q.getShippingAddressByOrderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getShippingAddressByOrderIDStmt: %w", cerr)
		}
	}
	if q.getSumOfCartItemsByUserIDStmt != nil {
		if cerr := q.getSumOfCartItemsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSumOfCartItemsByUserIDStmt: %w", cerr)
		}
	}
	if q.getTotalAmountOfCartItemsStmt != nil {
		if cerr := q.getTotalAmountOfCartItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalAmountOfCartItemsStmt: %w", cerr)
		}
	}
	if q.getUserIDFromOrderItemIDStmt != nil {
		if cerr := q.getUserIDFromOrderItemIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserIDFromOrderItemIDStmt: %w", cerr)
		}
	}
	if q.getValidCouponByNameStmt != nil {
		if cerr := q.getValidCouponByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getValidCouponByNameStmt: %w", cerr)
		}
	}
	if q.getVendorPaymentByOrderItemIDStmt != nil {
		if cerr := q.getVendorPaymentByOrderItemIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVendorPaymentByOrderItemIDStmt: %w", cerr)
		}
	}
	if q.getVendorPaymentsByDateRangeStmt != nil {
		if cerr := q.getVendorPaymentsByDateRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVendorPaymentsByDateRangeStmt: %w", cerr)
		}
	}
	if q.getVendorPaymentsBySellerIDStmt != nil {
		if cerr := q.getVendorPaymentsBySellerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVendorPaymentsBySellerIDStmt: %w", cerr)
		}
	}
	if q.getVendorPaymentsBySellerIDAndDateRangeStmt != nil {
		if cerr := q.getVendorPaymentsBySellerIDAndDateRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVendorPaymentsBySellerIDAndDateRangeStmt: %w", cerr)
		}
	}
	if q.updateOrderTotalAmountStmt != nil {
		if cerr := q.updateOrderTotalAmountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderTotalAmountStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                          DBTX
	tx                                          *sql.Tx
	addCartItemStmt                             *sql.Stmt
	addCouponStmt                               *sql.Stmt
	addOrderStmt                                *sql.Stmt
	addOrderITemStmt                            *sql.Stmt
	addPaymentStmt                              *sql.Stmt
	addShippingAddressStmt                      *sql.Stmt
	addVendorPaymentStmt                        *sql.Stmt
	cancelOrderByIDStmt                         *sql.Stmt
	cancelPaymentByOrderIDStmt                  *sql.Stmt
	cancelVendorPaymentByOrderItemIDStmt        *sql.Stmt
	cancelVendorPaymentsByOrderIDStmt           *sql.Stmt
	changeOrderItemStatusByIDStmt               *sql.Stmt
	decPaymentAmountByOrderItemIDStmt           *sql.Stmt
	deleteCartItemByUserIDAndProductIDStmt      *sql.Stmt
	deleteCartItemsByUserIDStmt                 *sql.Stmt
	deleteCouponByIDStmt                        *sql.Stmt
	deleteCouponByNameStmt                      *sql.Stmt
	deleteOrderByIDStmt                         *sql.Stmt
	editCartItemByIDStmt                        *sql.Stmt
	editCouponByIDStmt                          *sql.Stmt
	editCouponByNameStmt                        *sql.Stmt
	editOrderAmountByIDStmt                     *sql.Stmt
	editOrderItemStatusByIDStmt                 *sql.Stmt
	editPaymentByOrderIDStmt                    *sql.Stmt
	editPaymentStatusByIDStmt                   *sql.Stmt
	editPaymentStatusByOrderIDStmt              *sql.Stmt
	editVendorPaymentStatusByOrderItemIDStmt    *sql.Stmt
	getAllCouponsStmt                           *sql.Stmt
	getAllCouponsForAdminStmt                   *sql.Stmt
	getAllOrderItemsForAdminStmt                *sql.Stmt
	getAllOrdersStmt                            *sql.Stmt
	getCartItemByIDStmt                         *sql.Stmt
	getCartItemByUserIDAndProductIDStmt         *sql.Stmt
	getCartItemsByUserIDStmt                    *sql.Stmt
	getCouponByIDStmt                           *sql.Stmt
	getCouponByNameStmt                         *sql.Stmt
	getOrderByIDStmt                            *sql.Stmt
	getOrderItemByIDStmt                        *sql.Stmt
	getOrderItemByUserAndProductIDStmt          *sql.Stmt
	getOrderItemsByOrderIDStmt                  *sql.Stmt
	getOrderItemsBySellerIDStmt                 *sql.Stmt
	getOrderItemsBySellerIDAndDateRangeStmt     *sql.Stmt
	getOrderItemsByUserIDStmt                   *sql.Stmt
	getOrdersByUserIDStmt                       *sql.Stmt
	getPaymentByOrderIDStmt                     *sql.Stmt
	getProductFromCartByIDStmt                  *sql.Stmt
	getProductNameAndQuantityFromCartsByIDStmt  *sql.Stmt
	getReviewByUserAndProductIDStmt             *sql.Stmt
	getSellerIDFromOrderItemIDStmt              *sql.Stmt
	getShippingAddressByOrderIDStmt             *sql.Stmt
	getSumOfCartItemsByUserIDStmt               *sql.Stmt
	getTotalAmountOfCartItemsStmt               *sql.Stmt
	getUserIDFromOrderItemIDStmt                *sql.Stmt
	getValidCouponByNameStmt                    *sql.Stmt
	getVendorPaymentByOrderItemIDStmt           *sql.Stmt
	getVendorPaymentsByDateRangeStmt            *sql.Stmt
	getVendorPaymentsBySellerIDStmt             *sql.Stmt
	getVendorPaymentsBySellerIDAndDateRangeStmt *sql.Stmt
	updateOrderTotalAmountStmt                  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                          tx,
		tx:                                          tx,
		addCartItemStmt:                             q.addCartItemStmt,
		addCouponStmt:                               q.addCouponStmt,
		addOrderStmt:                                q.addOrderStmt,
		addOrderITemStmt:                            q.addOrderITemStmt,
		addPaymentStmt:                              q.addPaymentStmt,
		addShippingAddressStmt:                      q.addShippingAddressStmt,
		addVendorPaymentStmt:                        q.addVendorPaymentStmt,
		cancelOrderByIDStmt:                         q.cancelOrderByIDStmt,
		cancelPaymentByOrderIDStmt:                  q.cancelPaymentByOrderIDStmt,
		cancelVendorPaymentByOrderItemIDStmt:        q.cancelVendorPaymentByOrderItemIDStmt,
		cancelVendorPaymentsByOrderIDStmt:           q.cancelVendorPaymentsByOrderIDStmt,
		changeOrderItemStatusByIDStmt:               q.changeOrderItemStatusByIDStmt,
		decPaymentAmountByOrderItemIDStmt:           q.decPaymentAmountByOrderItemIDStmt,
		deleteCartItemByUserIDAndProductIDStmt:      q.deleteCartItemByUserIDAndProductIDStmt,
		deleteCartItemsByUserIDStmt:                 q.deleteCartItemsByUserIDStmt,
		deleteCouponByIDStmt:                        q.deleteCouponByIDStmt,
		deleteCouponByNameStmt:                      q.deleteCouponByNameStmt,
		deleteOrderByIDStmt:                         q.deleteOrderByIDStmt,
		editCartItemByIDStmt:                        q.editCartItemByIDStmt,
		editCouponByIDStmt:                          q.editCouponByIDStmt,
		editCouponByNameStmt:                        q.editCouponByNameStmt,
		editOrderAmountByIDStmt:                     q.editOrderAmountByIDStmt,
		editOrderItemStatusByIDStmt:                 q.editOrderItemStatusByIDStmt,
		editPaymentByOrderIDStmt:                    q.editPaymentByOrderIDStmt,
		editPaymentStatusByIDStmt:                   q.editPaymentStatusByIDStmt,
		editPaymentStatusByOrderIDStmt:              q.editPaymentStatusByOrderIDStmt,
		editVendorPaymentStatusByOrderItemIDStmt:    q.editVendorPaymentStatusByOrderItemIDStmt,
		getAllCouponsStmt:                           q.getAllCouponsStmt,
		getAllCouponsForAdminStmt:                   q.getAllCouponsForAdminStmt,
		getAllOrderItemsForAdminStmt:                q.getAllOrderItemsForAdminStmt,
		getAllOrdersStmt:                            q.getAllOrdersStmt,
		getCartItemByIDStmt:                         q.getCartItemByIDStmt,
		getCartItemByUserIDAndProductIDStmt:         q.getCartItemByUserIDAndProductIDStmt,
		getCartItemsByUserIDStmt:                    q.getCartItemsByUserIDStmt,
		getCouponByIDStmt:                           q.getCouponByIDStmt,
		getCouponByNameStmt:                         q.getCouponByNameStmt,
		getOrderByIDStmt:                            q.getOrderByIDStmt,
		getOrderItemByIDStmt:                        q.getOrderItemByIDStmt,
		getOrderItemByUserAndProductIDStmt:          q.getOrderItemByUserAndProductIDStmt,
		getOrderItemsByOrderIDStmt:                  q.getOrderItemsByOrderIDStmt,
		getOrderItemsBySellerIDStmt:                 q.getOrderItemsBySellerIDStmt,
		getOrderItemsBySellerIDAndDateRangeStmt:     q.getOrderItemsBySellerIDAndDateRangeStmt,
		getOrderItemsByUserIDStmt:                   q.getOrderItemsByUserIDStmt,
		getOrdersByUserIDStmt:                       q.getOrdersByUserIDStmt,
		getPaymentByOrderIDStmt:                     q.getPaymentByOrderIDStmt,
		getProductFromCartByIDStmt:                  q.getProductFromCartByIDStmt,
		getProductNameAndQuantityFromCartsByIDStmt:  q.getProductNameAndQuantityFromCartsByIDStmt,
		getReviewByUserAndProductIDStmt:             q.getReviewByUserAndProductIDStmt,
		getSellerIDFromOrderItemIDStmt:              q.getSellerIDFromOrderItemIDStmt,
		getShippingAddressByOrderIDStmt:             q.getShippingAddressByOrderIDStmt,
		getSumOfCartItemsByUserIDStmt:               q.getSumOfCartItemsByUserIDStmt,
		getTotalAmountOfCartItemsStmt:               q.getTotalAmountOfCartItemsStmt,
		getUserIDFromOrderItemIDStmt:                q.getUserIDFromOrderItemIDStmt,
		getValidCouponByNameStmt:                    q.getValidCouponByNameStmt,
		getVendorPaymentByOrderItemIDStmt:           q.getVendorPaymentByOrderItemIDStmt,
		getVendorPaymentsByDateRangeStmt:            q.getVendorPaymentsByDateRangeStmt,
		getVendorPaymentsBySellerIDStmt:             q.getVendorPaymentsBySellerIDStmt,
		getVendorPaymentsBySellerIDAndDateRangeStmt: q.getVendorPaymentsBySellerIDAndDateRangeStmt,
		updateOrderTotalAmountStmt:                  q.updateOrderTotalAmountStmt,
	}
}
