// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Coupon struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	DiscountType   string    `json:"discount_type"`
	TriggerPrice   float64   `json:"trigger_price"`
	DiscountAmount float64   `json:"discount_amount"`
	IsDeleted      bool      `json:"is_deleted"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
}

type Order struct {
	ID             uuid.UUID     `json:"id"`
	UserID         uuid.UUID     `json:"user_id"`
	TotalAmount    float64       `json:"total_amount"`
	CouponID       uuid.NullUUID `json:"coupon_id"`
	DiscountAmount float64       `json:"discount_amount"`
	NetAmount      float64       `json:"net_amount"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type OrderItem struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Price       float64   `json:"price"`
	Quantity    int32     `json:"quantity"`
	TotalAmount float64   `json:"total_amount"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Payment struct {
	ID            uuid.UUID      `json:"id"`
	OrderID       uuid.UUID      `json:"order_id"`
	Method        string         `json:"method"`
	Status        string         `json:"status"`
	TotalAmount   float64        `json:"total_amount"`
	TransactionID sql.NullString `json:"transaction_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Product struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Price       string    `json:"price"`
	Stock       int32     `json:"stock"`
	SellerID    uuid.UUID `json:"seller_id"`
	IsDeleted   bool      `json:"is_deleted"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ReturnRefund struct {
	ID                    uuid.UUID `json:"id"`
	UserID                uuid.UUID `json:"user_id"`
	OrderItemID           uuid.UUID `json:"order_item_id"`
	PaymentID             uuid.UUID `json:"payment_id"`
	ItemAmount            float64   `json:"item_amount"`
	DiscountRemovalAmount float64   `json:"discount_removal_amount"`
	RefundAmount          float64   `json:"refund_amount"`
	Status                string    `json:"status"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type Review struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	ProductID uuid.UUID      `json:"product_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	IsDeleted bool           `json:"is_deleted"`
	IsEdited  bool           `json:"is_edited"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type ShippingAddress struct {
	ID         uuid.UUID `json:"id"`
	OrderID    uuid.UUID `json:"order_id"`
	HouseName  string    `json:"house_name"`
	StreetName string    `json:"street_name"`
	Town       string    `json:"town"`
	District   string    `json:"district"`
	State      string    `json:"state"`
	Pincode    int32     `json:"pincode"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type VendorPayment struct {
	ID           uuid.UUID `json:"id"`
	OrderItemID  uuid.UUID `json:"order_item_id"`
	SellerID     uuid.UUID `json:"seller_id"`
	Status       string    `json:"status"`
	TotalAmount  float64   `json:"total_amount"`
	PlatformFee  float64   `json:"platform_fee"`
	CreditAmount float64   `json:"credit_amount"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
